
import Model.Beer;
import Model.BeerAttributeWeight;
import Model.BeerSimilarity;
import static com.alee.laf.filechooser.FileChooserViewType.table;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 5686563
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        this.setVisible(false);
        initComponents();
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images/Beer-icon.png"));
        ImageIcon icon = new ImageIcon(image);
        this.setIconImage(icon.getImage());
        
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        abvEntry = new javax.swing.JLabel();
        ibuEntry = new javax.swing.JLabel();
        styleEntry = new javax.swing.JLabel();
        ouncesEntry = new javax.swing.JLabel();
        ibuWeight = new javax.swing.JLabel();
        abvWeight = new javax.swing.JLabel();
        styleWeight = new javax.swing.JLabel();
        ouncesWeight = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TopBeer - Report");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setEnabled(false);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ABV (%)", "IBU", "OUNCES", "STYLE", "NAME", "BREWERY / STATE", "SIMILARITY (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportTable);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entries", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ABV (%)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("IBU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("STYLE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("OUNCES");

        abvEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        abvEntry.setForeground(new java.awt.Color(51, 51, 51));
        abvEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abvEntry.setText("5467867678");

        ibuEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ibuEntry.setForeground(new java.awt.Color(51, 51, 51));
        ibuEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ibuEntry.setText("5467867678");

        styleEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        styleEntry.setForeground(new java.awt.Color(51, 51, 51));
        styleEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        styleEntry.setText("5467867678");

        ouncesEntry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ouncesEntry.setForeground(new java.awt.Color(51, 51, 51));
        ouncesEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ouncesEntry.setText("5467867678");

        ibuWeight.setForeground(new java.awt.Color(51, 51, 51));
        ibuWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ibuWeight.setText("jLabel5");

        abvWeight.setForeground(new java.awt.Color(51, 51, 51));
        abvWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abvWeight.setText("jLabel5");

        styleWeight.setForeground(new java.awt.Color(51, 51, 51));
        styleWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        styleWeight.setText("jLabel5");

        ouncesWeight.setForeground(new java.awt.Color(51, 51, 51));
        ouncesWeight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ouncesWeight.setText("jLabel5");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Weight");

        processButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        processButton.setText("Back");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ibuEntry)
                            .addComponent(ouncesEntry)
                            .addComponent(styleEntry)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(abvEntry)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(abvWeight)
                                .addComponent(styleWeight)
                                .addComponent(ouncesWeight)
                                .addComponent(ibuWeight))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(processButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abvEntry)
                    .addComponent(abvWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibuEntry)
                    .addComponent(ibuWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(styleEntry)
                    .addComponent(styleWeight))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouncesEntry)
                    .addComponent(ouncesWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        Principal principal = new Principal();
        
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_processButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abvEntry;
    private javax.swing.JLabel abvWeight;
    private javax.swing.JLabel ibuEntry;
    private javax.swing.JLabel ibuWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel ouncesEntry;
    private javax.swing.JLabel ouncesWeight;
    private javax.swing.JButton processButton;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel styleEntry;
    private javax.swing.JLabel styleWeight;
    // End of variables declaration//GEN-END:variables

    void populateTabel(List<BeerSimilarity> beerSimilarity, Beer beer, BeerAttributeWeight baw) {
        // id, abv, ibu, ounces, style, name, brewery, similarity
        
        DefaultTableModel tableModel = (DefaultTableModel)reportTable.getModel();
        Object row[] = new Object[beerSimilarity.size()];
        
        abvEntry.setText(String.format("%.2f",beer.getAbv()));
        ibuEntry.setText(String.format("%.2f",beer.getIbu()));
        styleEntry.setText(beer.getStyle());
        ouncesEntry.setText(String.format("%.2f",beer.getOunces()));
        
        abvWeight.setText(String.format("%.2f", baw.getAbv()));
        ibuWeight.setText(String.format("%.2f", baw.getIbu()));
        styleWeight.setText(String.format("%.2f", baw.getStyle()));
        ouncesWeight.setText(String.format("%.2f", baw.getOunces()));
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        reportTable.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        reportTable.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        reportTable.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        reportTable.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        
        for(int i = 0; i < beerSimilarity.size(); i++)
        {
            row[0] = beerSimilarity.get(i).getBeer().getId();
            row[1] = String.format("%.2f",beerSimilarity.get(i).getBeer().getAbv()*100);
            row[2] = String.format("%.2f",beerSimilarity.get(i).getBeer().getIbu());
            row[3] = String.format("%.2f",beerSimilarity.get(i).getBeer().getOunces());
            row[4] = beerSimilarity.get(i).getBeer().getStyle();
            row[5] = beerSimilarity.get(i).getBeer().getName();
            row[6] = beerSimilarity.get(i).getBeer().getBrewery().getName()+ " / " +beerSimilarity.get(i).getBeer().getBrewery().getState();
            row[7] = String.format("%.4f", beerSimilarity.get(i).getSimilarity()*100);
            
            tableModel.addRow(row);
        }
        
        reportTable.setRowSelectionInterval(0, 0);
        
    }
}
